2025-05-25 18:50:19 - INFO - _internal.py - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:3002
 * Running on http://192.168.68.105:3002
2025-05-25 18:50:19 - INFO - _internal.py - [33mPress CTRL+C to quit[0m
2025-05-25 18:50:19 - INFO - _internal.py -  * Restarting with stat
2025-05-25 18:50:19 - WARNING - _internal.py -  * Debugger is active!
2025-05-25 18:50:19 - INFO - _internal.py -  * Debugger PIN: 374-470-396
2025-05-25 18:50:43 - INFO - routes.py - Fetching all bills from database
2025-05-25 18:51:13 - ERROR - routes.py - Error fetching bills: localhost:27017: [Errno 61] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 68339eab753cbe48849ec5ee, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 61] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
2025-05-25 18:51:13 - INFO - _internal.py - 127.0.0.1 - - [25/May/2025 18:51:13] "[35m[1mGET /api/bills HTTP/1.1[0m" 500 -
2025-05-25 18:52:36 - INFO - _internal.py -  * Detected change in '/Users/Shared/D/Projects/25utility_tracker/utility_tracker/backend/config.py', reloading
2025-05-25 18:52:36 - INFO - _internal.py -  * Restarting with stat
2025-05-25 18:52:36 - WARNING - _internal.py -  * Debugger is active!
2025-05-25 18:52:36 - INFO - _internal.py -  * Debugger PIN: 374-470-396
2025-05-25 18:52:45 - INFO - _internal.py -  * Detected change in '/Users/Shared/D/Projects/25utility_tracker/utility_tracker/backend/config.py', reloading
2025-05-25 18:52:46 - INFO - _internal.py -  * Restarting with stat
2025-05-25 18:52:46 - WARNING - _internal.py -  * Debugger is active!
2025-05-25 18:52:46 - INFO - _internal.py -  * Debugger PIN: 374-470-396
2025-05-25 18:53:27 - INFO - routes.py - Fetching all bills from database
2025-05-25 18:53:58 - ERROR - routes.py - Error fetching bills: localhost:27017: [Errno 61] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 68339f3e7e5e25779651785b, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 61] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
2025-05-25 18:53:58 - INFO - _internal.py - 127.0.0.1 - - [25/May/2025 18:53:58] "[35m[1mGET /api/bills HTTP/1.1[0m" 500 -
2025-05-25 18:55:01 - INFO - routes.py - Fetching all bills from database
2025-05-25 18:55:31 - ERROR - routes.py - Error fetching bills: localhost:27017: [Errno 61] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 68339f3e7e5e25779651785b, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 61] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
2025-05-25 18:55:31 - INFO - _internal.py - 127.0.0.1 - - [25/May/2025 18:55:31] "[35m[1mGET /api/bills HTTP/1.1[0m" 500 -
2025-05-25 18:56:13 - INFO - routes.py - Fetching current month's bills (05/2025)
2025-05-25 18:56:44 - ERROR - routes.py - Error fetching current bills: localhost:27017: [Errno 61] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 68339f3e7e5e25779651785b, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 61] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
2025-05-25 18:56:44 - INFO - _internal.py - 127.0.0.1 - - [25/May/2025 18:56:44] "[35m[1mGET /api/bills/current HTTP/1.1[0m" 500 -
2025-05-25 18:57:18 - INFO - _internal.py -  * Detected change in '/Users/Shared/D/Projects/25utility_tracker/utility_tracker/backend/routes.py', reloading
2025-05-25 18:57:18 - INFO - _internal.py -  * Restarting with stat
2025-05-25 18:57:18 - WARNING - _internal.py -  * Debugger is active!
2025-05-25 18:57:18 - INFO - _internal.py -  * Debugger PIN: 374-470-396
2025-05-25 18:59:22 - INFO - _internal.py - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:3002
 * Running on http://192.168.68.105:3002
2025-05-25 18:59:22 - INFO - _internal.py - [33mPress CTRL+C to quit[0m
2025-05-25 18:59:22 - INFO - _internal.py -  * Restarting with stat
2025-05-25 18:59:22 - WARNING - _internal.py -  * Debugger is active!
2025-05-25 18:59:22 - INFO - _internal.py -  * Debugger PIN: 374-470-396
2025-05-25 18:59:29 - INFO - routes.py - Fetching current month's bills (05/2025)
2025-05-25 18:59:29 - INFO - _internal.py - 127.0.0.1 - - [25/May/2025 18:59:29] "GET /api/bills/current HTTP/1.1" 200 -
2025-05-25 18:59:38 - INFO - routes.py - Fetching all bills from database
2025-05-25 18:59:38 - INFO - _internal.py - 127.0.0.1 - - [25/May/2025 18:59:38] "GET /api/bills HTTP/1.1" 200 -
